version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: nestjs_db
    environment:
      MYSQL_ROOT_PASSWORD: a223344a
      MYSQL_DATABASE: calcdb
      MYSQL_USER: calcuser
      MYSQL_PASSWORD: calcpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: calcuser
      DB_PASSWORD: calcpass
      DB_DATABASE: calcdb

volumes:
  mysql_data:
